### ISSUE TITLE
Omnipay V3 Support

### ISSUE THREAD

**Issue by skurvish** [Transportersio/omnipay-square#3]
Do you have plans for this?

**Comment by mnwalker** [comment]
Yes definitely, omnipay has been holding our system back onto older laravel versions for far too long.
Trouble right now is dev resources are tied down with other projects.

If you are a developer and could assist, happy to accept PR and add you to this repo.
If not, we will complete this upgrade when get a chance, but expect likely 2-3 months, possibly longer.

**Comment by skurvish** [comment]
I am a developer, let me have a look and see what the required changes are and determine if it is a project I want to take on right now. This would be one step in a multi-step development project.

**Comment by gocherrytree** [comment]
we also need square for a project so will post our changes to get compatibility with omnipay v3 once complete

**Comment by skurvish** [comment]
Ass a follow up I am using the V2 compatible version so have not looked at a V3 port.

**Comment by skurvish** [comment]
V3 now working fine.
