### ISSUE TITLE
Charge using the square nonce

### ISSUE THREAD

**Issue by skurvish** [Transportersio/omnipay-square#4]
Not sure if this is the right place to ask this, but I am trying to process a charge through Omnipay-Square using the nonce provided by the Square Payment Form. When the form is submitted I receive a nonce. Below is the code I am trying to use:

		$gateway = Omnipay::create('Square');
		$gateway->initialize(array('accessToken' => $data->access_token, 'locationId' => $data->locationId));
		$items = array(
			array(
				'name' => "BBQ Six",
				'price' => "5.00",
				'quantity' => 1)
			);
		$response = $gateway->purchase([
			'amount' => $data->amount,
			'currency' => $data->currency,
			'nonce' => $nonce,
			'items' => $items
		])->send();

The response comes back successful but the getData has a redirect URL in it which just takes you to a square payment form. There is nothing returned by the getMessage() call.

Any ideas what is going wrong here?

**Comment by skurvish** [comment]
No ideas? Are nonces not supported with this plugin?

**Comment by mikeybeck** [comment]
I'm pretty sure the nonce is actually _required_ for it to work.  
Do you need to include an idempotency key - something like this in the purchase array?
`'idempotencyKey' => uniqid(),`

**Comment by skurvish** [comment]
I don't see anywhere in the Square code or samples that it uses the nonce. I suspect that is why it is redirecting to a payment page. Not sure about the idempotencyKey, I also don't see this documented anywhere.

**Comment by mikeybeck** [comment]
I can't remember how I figured it out but I know that I couldn't get it working without both the nonce and idempotencyKey present.  I do recall having to refer to the Square Documentation though.  
It says [here](https://docs.connect.squareup.com/api/connect/v2#idempotencykeys) that an idempotency key is required for the charge endpoint, which I'm pretty sure is what you're using.

**Comment by mnwalker** [comment]
Currently overseas so not able to dig into this fully, but if either of you
have any fixes or improvements for this module I'm happy to merge a PR or
add you to the repo.

**Comment by mikeybeck** [comment]
@skurvish Ah, so sorry!  I just checked my fork of the repo and see that it makes significant changes to the original, and therefore my above comments don't apply.  Weird thing is, it was only a few months ago but I barely remember having written most of that code.  
I'm not sure that I trust my memory around this now, but I think I must have added the nonce stuff in because it was the only way to make a transaction without redirecting.

If you want to give my fork a try that'd be cool.  If it works for you I could make a PR, although it'd probably need some tidying up and tests added.

Thanks @mnwalker - I'm keen to make a PR but I at least need to add some tests first.  While my fork works for me, there's a good chance I've made changes which break other stuff.  Will see what @skurvish says.

**Comment by mikeybeck** [comment]
Excellent, thanks!

**Comment by skurvish** [comment]
@mikeybeck I have started testing with your fork and have made some progress. It is complicated by the fact that Square does not make sandbox transactions visible in the dashboard (unlike Stripe). So I do not know if the transaction was successful or not.

Couple of things. Do you or anyone at transportersio have a script to pull the list of transactions from square? I coded something up but it always wants to process a charge instead of returning the transactionlist. Second, @mikeybeck you do not have an issues option on your git so I cannot post any problems there. Alternatively you can forward me you email address and I can contact you directly. You can reach me at achartier at admiralsecure dot com.

Good progress but complicated by Square api.

**Comment by mikeybeck** [comment]
That's great!  Yeah, the lack of sandbox transaction data does make things difficult.  However, when you make a transaction you should receive a response which tells you whether the transaction was successful.  Are you getting that?

I don't have a way to get the transaction list from Square; I just store the response data and refer to that.  
I've added the issues option to the repo and added you as a collaborator as well.

**Comment by skurvish** [comment]
OK, I have discovered a fundamental issue with my install. As I am running PHP , 7.1 and Omnipay V2 I was getting the very first version of your repo. I tried to muck around to get 1.06 but it has an Omnipay V3 dependancy so for now I have simply copied the 1.06 files over top of the 1.0 install. I will continue to work from there and report any issue on the mikeybeck repo.

**Comment by skurvish** [comment]
@mnwalker we have the nonce payment processing complete and tested. I have also implemented refunds and transactions lists. I have been waiting for @mikeybeck to get back to me on PR of these changes but he has been MIA for the last 3 weeks.

I am able to PR them myself if you would like. I would really like to get this done and installable via composer so I can release my project. How would you like me to proceed?

**Comment by skurvish** [comment]
Testing on my end was V2 but Mikey had V3 in his testing so I expect it will work on both. I will work on a PR over the next few days.

**Comment by skurvish** [comment]
PR submitted.

**Comment by skurvish** [comment]
Has anyone had a chance to look at this?

**Comment by skurvish** [comment]
@mnwalker  I note that he Travis CI build failed, am I supposed to do something about this?

Any feedback from anyone?

**Comment by Alofoxx** [comment]
@skurvish your ci build failed due to PSR2 standard checks. Such as the use of tabs where spaces should be and general formatting. 
you can click on the link for details on the travis ci site.

**Comment by skurvish** [comment]
@Alofoxx Am I supposed to modify the code to conform to these standards? Sorry, I have not had this issue come up with any other git system I have contributed to before.

**Comment by skurvish** [comment]
Please run checks again. I have modified to conform to PSR2. I think I have them all.

**Comment by skurvish** [comment]
@mnwalker The changes have been PR's and the test run successfully as on Jan 6. What more needs to be done to get these changes merged and available through composer?

**Comment by Alofoxx** [comment]
@skurvish why did you change the composer.json package to blasttech/omnipay-square/ ?

**Comment by skurvish** [comment]
This was the repository I needed to get the original changes for the nonce from. It was Mikeybeck's. It does not need to stay that way.

**Comment by skurvish** [comment]
Do you want me to revert it in the PR?

**Comment by skurvish** [comment]
OK. I give up. I have spent far more time on this (especially with all the PSR2 stuff) than I wanted. I started to use the original code for a project only to discover the nonce stuff did not work. As a result I ended up implementing a Stripe solution. I came back to this only because MikeyBeck advised he had a version that worked with the nonce and since I had already done the stripe work and I was in the mindset I decided I would go ahead and finish the Square implementation for completeness.

I don't need the Square support and I certainly don't need to keep hounding you guys to merge the changes. So I am walking away, you can do what you want with the PR.

**Comment by gl3nda85** [comment]
@skurvish can you check mikeybecks repo, i merged a bunch of square similar stuff

**Comment by mnwalker** [comment]
apologies everyone, just discovered these requests, not sure whats happened to my notifications.
Have merged the PR and invited @skurvish and @mikeybeck to be collaborators on the repo.

**Comment by skurvish** [comment]
Thanks @mnwalker , question, are the changes now available through composer?

**Comment by mnwalker** [comment]
They are now, just had to tag a release and update the packagist webhook.
Have set to version 2.0.0 to avoid breaking any earlier systems, update you version ref and should get latest code.

Going forward you should be able to create releases as well @skurvish after merging any pull requests
