### ISSUE TITLE
Composer Omnipay V3 Requirement

### ISSUE THREAD

**Issue by skurvish** [Transportersio/omnipay-square#7]
@mnwalker  The composer files for this release require V3 of Omnipay but the code itself does not.  I did all my update integration using V2 so I know if works fine. I would like to be able to install this omnipay-square through composer on an OmniPay V2 system. 

Can this repository be changed to allow either version installed? Is there some way I can override the requirement in my composer.json file?

Other ideas? Thanks.

**Comment by mnwalker** [comment]
It should be possible to allow both in composer but not able to run tests
at the moment, hopefully can get a chance next week.

Or if can set the required composer tag into a PR can merge and tag a
release.

**Comment by skurvish** [comment]
@mnwalker 
I was able to override the requirement in my own json file by using the following:
`        "omnipay/common": "2.5.2 as 3",
`
and
`        "omnipay/tests": "v2.1.1 as 3"
`
Not sure if this is a good way to solve the issue for me or not. Thoughts?

**Comment by skurvish** [comment]
As it turns out I no longer require V2, the base system has been updated to V3. Closing this.
